In [93]:
%load_ext autoreload
%autoreload 2

import sys
import os
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix

sys.path.append(os.path.abspath('ml-models'))
from mlmodels.Models import Models

from sklearn.metrics import confusion_matrix

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [94]:
#Defining random seeds
with open('./random_seeds.txt', 'r') as f:
    random_seeds = eval(f.read())

### Construct dataset

In [95]:
# Original dataset
data = pd.read_csv('data/tables/generated/features_dataset.csv', index_col=0)
# Use only static features
dynamic_features = data[[col for col in data.columns if 'min' in col or 'mean' in col]]
data = data.drop(columns=[col for col in data.columns if 'min' in col or 'mean' in col])
data

,segid,resid,mutation,phenotype,d_volume,d_hydropathy_KD,d_MW,d_pi,d_rogov,Rif_distance,...,phi,psi,n_hbond_acceptors,n_hbond_donors,SASA,snap2_score,deep_ddG,rasp_score,temp_factor,secondary_structure
2,C,639,E639D,0,-27.3,0.0,-14.0,-0.45,0.109,34.015193,...,-72.58,-54.68,0.0,0.0,107.910414,50,-0.152,0.254674,41.400002,0
3,C,113,V113I,0,26.7,0.3,14.1,0.06,0.494,24.626817,...,-55.57,-55.02,2.0,0.0,46.996241,-95,0.471,0.222572,36.919998,1
4,C,642,G642S,0,28.9,-0.4,30.0,-0.29,0.120,42.448172,...,169.90,-149.75,1.0,1.0,0.226439,48,-2.495,0.548394,32.490002,2
5,C,751,I751V,0,-26.7,-0.3,-14.1,-0.06,0.494,27.986912,...,-161.65,154.98,1.0,1.0,23.895392,-91,-0.242,0.287591,19.900000,2
6,C,944,K944N,0,-54.5,0.4,-14.1,-4.33,0.197,59.941562,...,60.77,28.12,0.0,0.0,208.845293,-73,0.025,0.215516,86.489998,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,C,445,H445F,1,36.7,6.0,10.0,-2.11,-0.016,9.683248,...,-66.73,-38.07,1.0,2.0,6.609119,92,-0.684,0.201490,16.459999,1
263,C,434,M434I,1,3.8,2.6,-18.0,0.28,-0.452,9.843524,...,-62.15,126.41,0.0,1.0,7.242104,93,-1.393,0.290369,17.299999,3
264,C,262,V262A,1,-51.4,-2.4,-28.0,0.04,0.232,56.595298,...,-126.69,153.98,0.0,0.0,95.032454,-82,-0.214,0.275822,133.350006,3
265,C,582,S582A,1,-0.4,2.6,-16.0,0.32,0.249,18.638826,...,-95.24,-170.26,1.0,0.0,0.000000,29,-1.548,0.237018,18.350000,0
266,C,378,L378R,1,6.7,-8.3,43.0,4.78,-0.090,17.636419,...,-59.74,-39.22,0.0,1.0,9.222732,60,-5.106,0.491561,21.850000,1

### Select for mutations outside RRDR only and with four key features

In [96]:
#Mutations outside RRDR
outside_rrdr = data[((data.resid < 426) | (data.resid > 452))]
print(outside_rrdr)

    segid  resid mutation  phenotype  d_volume  d_hydropathy_KD  d_MW  d_pi  \
2       C    639    E639D          0     -27.3              0.0 -14.0 -0.45
3       C    113    V113I          0      26.7              0.3  14.1  0.06
4       C    642    G642S          0      28.9             -0.4  30.0 -0.29
5       C    751    I751V          0     -26.7             -0.3 -14.1 -0.06
6       C    944    K944N          0     -54.5              0.4 -14.1 -4.33
..    ...    ...      ...        ...       ...              ...   ...   ...
258     C    731    L731P          1     -54.0             -5.4 -16.1  0.32
260     C    493    S493R          1      84.4             -3.7  69.1  5.08
264     C    262    V262A          1     -51.4             -2.4 -28.0  0.04
265     C    582    S582A          1      -0.4              2.6 -16.0  0.32
266     C    378    L378R          1       6.7             -8.3  43.0  4.78

     d_rogov  Rif_distance  ...     phi     psi  n_hbond_acceptors  \
2      0.109     34.015193  ...  -72.58  -54.68                0.0
3      0.494     24.626817  ...  -55.57  -55.02                2.0
4      0.120     42.448172  ...  169.90 -149.75                1.0
5      0.494     27.986912  ... -161.65  154.98                1.0
6      0.197     59.941562  ...   60.77   28.12                0.0
..       ...           ...  ...     ...     ...                ...
258   -0.159     33.058292  ... -113.90  157.33                1.0
260    0.127     13.468693  ... -122.64  137.10                1.0
264    0.232     56.595298  ... -126.69  153.98                0.0
265    0.249     18.638826  ...  -95.24 -170.26                1.0
266   -0.090     17.636419  ...  -59.74  -39.22                0.0

     n_hbond_donors        SASA  snap2_score  deep_ddG  rasp_score  \
2               0.0  107.910414           50    -0.152    0.254674
3               0.0   46.996241          -95     0.471    0.222572
4               1.0    0.226439           48    -2.495    0.548394
5               1.0   23.895392          -91    -0.242    0.287591
6               0.0  208.845293          -73     0.025    0.215516
..              ...         ...          ...       ...         ...
258             1.0    0.000000           75    -5.617    0.925078
260             0.0    1.338677           26    -2.704    0.246800
264             0.0   95.032454          -82    -0.214    0.275822
265             0.0    0.000000           29    -1.548    0.237018
266             1.0    9.222732           60    -5.106    0.491561

     temp_factor  secondary_structure
2      41.400002                    0
3      36.919998                    1
4      32.490002                    2
5      19.900000                    2
6      86.489998                    0
..           ...                  ...
258    21.740000                    2
260    20.940001                    2
264   133.350006                    3
265    18.350000                    0
266    21.850000                    1

[216 rows x 26 columns]

In [97]:
feature_list = ['Rif_distance', 'RNA_distance', 'snap2_score', 'temp_factor']
features_and_label = feature_list + ['phenotype']

print ("Data with features:", features_and_label)

Data with features: ['Rif_distance', 'RNA_distance', 'snap2_score', 'temp_factor', 'phenotype']

In [98]:
data_outside_rrdr = outside_rrdr[features_and_label]
print(data_outside_rrdr)

     Rif_distance  RNA_distance  snap2_score  temp_factor  phenotype
2       34.015193     42.798608           50    41.400002          0
3       24.626817     35.774887          -95    36.919998          0
4       42.448172     49.686496           48    32.490002          0
5       27.986912     32.846026          -91    19.900000          0
6       59.941562     56.670554          -73    86.489998          0
..            ...           ...          ...          ...        ...
258     33.058292     23.530022           75    21.740000          1
260     13.468693     21.002388           26    20.940001          1
264     56.595298     65.031517          -82   133.350006          1
265     18.638826     23.573846           29    18.350000          1
266     17.636419     31.834717           60    21.850000          1

[216 rows x 5 columns]

In [99]:
phenotypes_nonRRDR = data_outside_rrdr["phenotype"]
phenotypes_nonRRDR

2      0
3      0
4      0
5      0
6      0
      ..
258    1
260    1
264    1
265    1
266    1
Name: phenotype, Length: 216, dtype: int64

In [100]:
x_nonRRDR = data_outside_rrdr[feature_list]
x_nonRRDR

     Rif_distance  RNA_distance  snap2_score  temp_factor
2       34.015193     42.798608           50    41.400002
3       24.626817     35.774887          -95    36.919998
4       42.448172     49.686496           48    32.490002
5       27.986912     32.846026          -91    19.900000
6       59.941562     56.670554          -73    86.489998
..            ...           ...          ...          ...
258     33.058292     23.530022           75    21.740000
260     13.468693     21.002388           26    20.940001
264     56.595298     65.031517          -82   133.350006
265     18.638826     23.573846           29    18.350000
266     17.636419     31.834717           60    21.850000

[216 rows x 4 columns]

### Get DT model trained on original dataset

In [101]:
model_type = ['DT']
all_models_results_original_DT = {model_type: [] for model_type in model_types}

for model_type in model_types:
    for seed in random_seeds:
        model = Models(
            {"all": data[features_and_label]},
            model_type,
            "recall",
            random_seed=seed,
            test_fraction=0.20,
            verbose=False,
            output_plots=False,
        )
        output_original_DT = model.returning_output(output_plots=False)
        all_models_results_original_DT[model_type].append(output_original_DT)

In [102]:
all_models_results_original_DT

{'DT': [{'Precision': 0.6666666666666666,
   'Sensitivity': 0.8888888888888888,
   'Specificity': 0.9090909090909091,
   'F1_Score': 0.761904761904762,
   'FPR': 0.09090909090909094,
   'VME': 9.090909090909092,
   'ME': 11.11111111111111,
   'Confusion_matrix': array([[40,  4],
          [ 1,  8]]),
   'ROC_AUC': 0.8952020202020202,
   'Precision_shifted': 0.6666666666666666,
   'Sensitivity_shifted': 0.8888888888888888,
   'Specificity_shifted': 0.9090909090909091,
   'F1_Score_shifted': 0.761904761904762,
   'FPR_shifted': 0.09090909090909094,
   'VME_shifted': 9.090909090909092,
   'ME_shifted': 11.11111111111111,
   'Confusion_matrix_shifted': array([[40,  4],
          [ 1,  8]])},
  {'Precision': 1.0,
   'Sensitivity': 0.8888888888888888,
   'Specificity': 1.0,
   'F1_Score': 0.9411764705882353,
   'FPR': 0.0,
   'VME': 0.0,
   'ME': 11.11111111111111,
   'Confusion_matrix': array([[44,  0],
          [ 1,  8]]),
   'ROC_AUC': 0.9406565656565656,
   'Precision_shifted': 1.0,
   'Sensitivity_shifted': 0.8888888888888888,
   'Specificity_shifted': 1.0,
   'F1_Score_shifted': 0.9411764705882353,
   'FPR_shifted': 0.0,
   'VME_shifted': 0.0,
   'ME_shifted': 11.11111111111111,
   'Confusion_matrix_shifted': array([[44,  0],
          [ 1,  8]])},
  {'Precision': 0.7,
   'Sensitivity': 1.0,
   'Specificity': 0.9347826086956522,
   'F1_Score': 0.8235294117647058,
   'FPR': 0.06521739130434778,
   'VME': 6.521739130434782,
   'ME': 0.0,
   'Confusion_matrix': array([[43,  3],
          [ 0,  7]]),
   'ROC_AUC': 0.967391304347826,
   'Precision_shifted': 0.7,
   'Sensitivity_shifted': 1.0,
   'Specificity_shifted': 0.9347826086956522,
   'F1_Score_shifted': 0.8235294117647058,
   'FPR_shifted': 0.06521739130434778,
   'VME_shifted': 6.521739130434782,
   'ME_shifted': 0.0,
   'Confusion_matrix_shifted': array([[43,  3],
          [ 0,  7]])},
  {'Precision': 0.8181818181818182,
   'Sensitivity': 0.9,
   'Specificity': 0.9534883720930233,
   'F1_Score': 0.8571428571428572,
   'FPR': 0.046511627906976716,
   'VME': 4.651162790697675,
   'ME': 10.0,
   'Confusion_matrix': array([[41,  2],
          [ 1,  9]]),
   'ROC_AUC': 0.9267441860465117,
   'Precision_shifted': 0.8181818181818182,
   'Sensitivity_shifted': 0.9,
   'Specificity_shifted': 0.9534883720930233,
   'F1_Score_shifted': 0.8571428571428572,
   'FPR_shifted': 0.046511627906976716,
   'VME_shifted': 4.651162790697675,
   'ME_shifted': 10.0,
   'Confusion_matrix_shifted': array([[41,  2],
          [ 1,  9]])},
  {'Precision': 1.0,
   'Sensitivity': 0.7,
   'Specificity': 1.0,
   'F1_Score': 0.8235294117647058,
   'FPR': 0.0,
   'VME': 0.0,
   'ME': 30.0,
   'Confusion_matrix': array([[43,  0],
          [ 3,  7]]),
   'ROC_AUC': 0.7999999999999999,
   'Precision_shifted': 1.0,
   'Sensitivity_shifted': 0.7,
   'Specificity_shifted': 1.0,
   'F1_Score_shifted': 0.8235294117647058,
   'FPR_shifted': 0.0,
   'VME_shifted': 0.0,
   'ME_shifted': 30.0,
   'Confusion_matrix_shifted': array([[43,  0],
          [ 3,  7]])},
  {'Precision': 0.7142857142857143,
   'Sensitivity': 0.9090909090909091,
   'Specificity': 0.9047619047619048,
   'F1_Score': 0.8,
   'FPR': 0.09523809523809523,
   'VME': 9.523809523809524,
   'ME': 9.090909090909092,
   'Confusion_matrix': array([[38,  4],
          [ 1, 10]]),
   'ROC_AUC': 0.8917748917748918,
   'Precision_shifted': 0.7142857142857143,
   'Sensitivity_shifted': 0.9090909090909091,
   'Specificity_shifted': 0.9047619047619048,
   'F1_Score_shifted': 0.8,
   'FPR_shifted': 0.09523809523809523,
   'VME_shifted': 9.523809523809524,
   'ME_shifted': 9.090909090909092,
   'Confusion_matrix_shifted': array([[38,  4],
          [ 1, 10]])},
  {'Precision': 0.75,
   'Sensitivity': 1.0,
   'Specificity': 0.9318181818181818,
   'F1_Score': 0.8571428571428571,
   'FPR': 0.06818181818181823,
   'VME': 6.8181818181818175,
   'ME': 0.0,
   'Confusion_matrix': array([[41,  3],
          [ 0,  9]]),
   'ROC_AUC': 0.9659090909090908,
   'Precision_shifted': 0.75,
   'Sensitivity_shifted': 1.0,
   'Specificity_shifted': 0.9318181818181818,
   'F1_Score_shifted': 0.8571428571428571,
   'FPR_shifted': 0.06818181818181823,
   'VME_shifted': 6.8181818181818175,
   'ME_shifted': 0.0,
   'Confusion_matrix_shifted': array([[41,  3],
          [ 0,  9]])},
  {'Precision': 0.7142857142857143,
   'Sensitivity': 0.8333333333333334,
   'Specificity': 0.9024390243902439,
   'F1_Score': 0.7692307692307692,
   'FPR': 0.09756097560975607,
   'VME': 9.75609756097561,
   'ME': 16.666666666666664,
   'Confusion_matrix': array([[37,  4],
          [ 2, 10]]),
   'ROC_AUC': 0.8678861788617888,
   'Precision_shifted': 0.7142857142857143,
   'Sensitivity_shifted': 0.8333333333333334,
   'Specificity_shifted': 0.9024390243902439,
   'F1_Score_shifted': 0.7692307692307692,
   'FPR_shifted': 0.09756097560975607,
   'VME_shifted': 9.75609756097561,
   'ME_shifted': 16.666666666666664,
   'Confusion_matrix_shifted': array([[37,  4],
          [ 2, 10]])},
  {'Precision': 1.0,
   'Sensitivity': 1.0,
   'Specificity': 1.0,
   'F1_Score': 1.0,
   'FPR': 0.0,
   'VME': 0.0,
   'ME': 0.0,
   'Confusion_matrix': array([[48,  0],
          [ 0,  5]]),
   'ROC_AUC': 1.0,
   'Precision_shifted': 1.0,
   'Sensitivity_shifted': 1.0,
   'Specificity_shifted': 1.0,
   'F1_Score_shifted': 1.0,
   'FPR_shifted': 0.0,
   'VME_shifted': 0.0,
   'ME_shifted': 0.0,
   'Confusion_matrix_shifted': array([[48,  0],
          [ 0,  5]])},
  {'Precision': 1.0,
   'Sensitivity': 0.8235294117647058,
   'Specificity': 1.0,
   'F1_Score': 0.9032258064516129,
   'FPR': 0.0,
   'VME': 0.0,
   'ME': 17.647058823529413,
   'Confusion_matrix': array([[36,  0],
          [ 3, 14]]),
   'ROC_AUC': 0.940359477124183,
   'Precision_shifted': 1.0,
   'Sensitivity_shifted': 0.8235294117647058,
   'Specificity_shifted': 1.0,
   'F1_Score_shifted': 0.9032258064516129,
   'FPR_shifted': 0.0,
   'VME_shifted': 0.0,
   'ME_shifted': 17.647058823529413,
   'Confusion_matrix_shifted': array([[36,  0],
          [ 3, 14]])},
  {'Precision': 0.9,
   'Sensitivity': 0.9,
   'Specificity': 0.9767441860465116,
   'F1_Score': 0.9,
   'FPR': 0.023255813953488413,
   'VME': 2.3255813953488373,
   'ME': 10.0,
   'Confusion_matrix': array([[42,  1],
          [ 1,  9]]),
   'ROC_AUC': 0.9360465116279069,
   'Precision_shifted': 0.9,
   'Sensitivity_shifted': 0.9,
   'Specificity_shifted': 0.9767441860465116,
   'F1_Score_shifted': 0.9,
   'FPR_shifted': 0.023255813953488413,
   'VME_shifted': 2.3255813953488373,
   'ME_shifted': 10.0,
   'Confusion_matrix_shifted': array([[42,  1],
          [ 1,  9]])},
  {'Precision': 0.6153846153846154,
   'Sensitivity': 0.8888888888888888,
   'Specificity': 0.8863636363636364,
   'F1_Score': 0.7272727272727274,
   'FPR': 0.11363636363636365,
   'VME': 11.363636363636363,
   'ME': 11.11111111111111,
   'Confusion_matrix': array([[39,  5],
          [ 1,  8]]),
   'ROC_AUC': 0.9191919191919192,
   'Precision_shifted': 0.6153846153846154,
   'Sensitivity_shifted': 0.8888888888888888,
   'Specificity_shifted': 0.8863636363636364,
   'F1_Score_shifted': 0.7272727272727274,
   'FPR_shifted': 0.11363636363636365,
   'VME_shifted': 11.363636363636363,
   'ME_shifted': 11.11111111111111,
   'Confusion_matrix_shifted': array([[39,  5],
          [ 1,  8]])},
  {'Precision': 1.0,
   'Sensitivity': 0.7142857142857143,
   'Specificity': 1.0,
   'F1_Score': 0.8333333333333333,
   'FPR': 0.0,
   'VME': 0.0,
   'ME': 28.57142857142857,
   'Confusion_matrix': array([[46,  0],
          [ 2,  5]]),
   'ROC_AUC': 0.9130434782608695,
   'Precision_shifted': 1.0,
   'Sensitivity_shifted': 0.7142857142857143,
   'Specificity_shifted': 1.0,
   'F1_Score_shifted': 0.8333333333333333,
   'FPR_shifted': 0.0,
   'VME_shifted': 0.0,
   'ME_shifted': 28.57142857142857,
   'Confusion_matrix_shifted': array([[46,  0],
          [ 2,  5]])},
  {'Precision': 0.7,
   'Sensitivity': 1.0,
   'Specificity': 0.9347826086956522,
   'F1_Score': 0.8235294117647058,
   'FPR': 0.06521739130434778,
   'VME': 6.521739130434782,
   'ME': 0.0,
   'Confusion_matrix': array([[43,  3],
          [ 0,  7]]),
   'ROC_AUC': 0.967391304347826,
   'Precision_shifted': 0.7,
   'Sensitivity_shifted': 1.0,
   'Specificity_shifted': 0.9347826086956522,
   'F1_Score_shifted': 0.8235294117647058,
   'FPR_shifted': 0.06521739130434778,
   'VME_shifted': 6.521739130434782,
   'ME_shifted': 0.0,
   'Confusion_matrix_shifted': array([[43,  3],
          [ 0,  7]])},
  {'Precision': 0.8888888888888888,
   'Sensitivity': 0.8888888888888888,
   'Specificity': 0.9772727272727273,
   'F1_Score': 0.8888888888888888,
   'FPR': 0.022727272727272707,
   'VME': 2.272727272727273,
   'ME': 11.11111111111111,
   'Confusion_matrix': array([[43,  1],
          [ 1,  8]]),
   'ROC_AUC': 0.9292929292929293,
   'Precision_shifted': 0.8888888888888888,
   'Sensitivity_shifted': 0.8888888888888888,
   'Specificity_shifted': 0.9772727272727273,
   'F1_Score_shifted': 0.8888888888888888,
   'FPR_shifted': 0.022727272727272707,
   'VME_shifted': 2.272727272727273,
   'ME_shifted': 11.11111111111111,
   'Confusion_matrix_shifted': array([[43,  1],
          [ 1,  8]])},
  {'Precision': 0.9,
   'Sensitivity': 0.75,
   'Specificity': 0.975609756097561,
   'F1_Score': 0.8181818181818182,
   'FPR': 0.024390243902439046,
   'VME': 2.4390243902439024,
   'ME': 25.0,
   'Confusion_matrix': array([[40,  1],
          [ 3,  9]]),
   'ROC_AUC': 0.8597560975609756,
   'Precision_shifted': 0.9,
   'Sensitivity_shifted': 0.75,
   'Specificity_shifted': 0.975609756097561,
   'F1_Score_shifted': 0.8181818181818182,
   'FPR_shifted': 0.024390243902439046,
   'VME_shifted': 2.4390243902439024,
   'ME_shifted': 25.0,
   'Confusion_matrix_shifted': array([[40,  1],
          [ 3,  9]])},
  {'Precision': 1.0,
   'Sensitivity': 0.6666666666666666,
   'Specificity': 1.0,
   'F1_Score': 0.8,
   'FPR': 0.0,
   'VME': 0.0,
   'ME': 33.33333333333333,
   'Confusion_matrix': array([[41,  0],
          [ 4,  8]]),
   'ROC_AUC': 0.7520325203252032,
   'Precision_shifted': 1.0,
   'Sensitivity_shifted': 0.6666666666666666,
   'Specificity_shifted': 1.0,
   'F1_Score_shifted': 0.8,
   'FPR_shifted': 0.0,
   'VME_shifted': 0.0,
   'ME_shifted': 33.33333333333333,
   'Confusion_matrix_shifted': array([[41,  0],
          [ 4,  8]])},
  {'Precision': 0.7,
   'Sensitivity': 0.7777777777777778,
   'Specificity': 0.9318181818181818,
   'F1_Score': 0.7368421052631577,
   'FPR': 0.06818181818181823,
   'VME': 6.8181818181818175,
   'ME': 22.22222222222222,
   'Confusion_matrix': array([[41,  3],
          [ 2,  7]]),
   'ROC_AUC': 0.7512626262626263,
   'Precision_shifted': 0.7,
   'Sensitivity_shifted': 0.7777777777777778,
   'Specificity_shifted': 0.9318181818181818,
   'F1_Score_shifted': 0.7368421052631577,
   'FPR_shifted': 0.06818181818181823,
   'VME_shifted': 6.8181818181818175,
   'ME_shifted': 22.22222222222222,
   'Confusion_matrix_shifted': array([[41,  3],
          [ 2,  7]])},
  {'Precision': 0.7777777777777778,
   'Sensitivity': 0.7777777777777778,
   'Specificity': 0.9545454545454546,
   'F1_Score': 0.7777777777777778,
   'FPR': 0.045454545454545414,
   'VME': 4.545454545454546,
   'ME': 22.22222222222222,
   'Confusion_matrix': array([[42,  2],
          [ 2,  7]]),
   'ROC_AUC': 0.9166666666666667,
   'Precision_shifted': 0.7777777777777778,
   'Sensitivity_shifted': 0.7777777777777778,
   'Specificity_shifted': 0.9545454545454546,
   'F1_Score_shifted': 0.7777777777777778,
   'FPR_shifted': 0.045454545454545414,
   'VME_shifted': 4.545454545454546,
   'ME_shifted': 22.22222222222222,
   'Confusion_matrix_shifted': array([[42,  2],
          [ 2,  7]])},
  {'Precision': 0.7777777777777778,
   'Sensitivity': 0.7,
   'Specificity': 0.9534883720930233,
   'F1_Score': 0.7368421052631577,
   'FPR': 0.046511627906976716,
   'VME': 4.651162790697675,
   'ME': 30.0,
   'Confusion_matrix': array([[41,  2],
          [ 3,  7]]),
   'ROC_AUC': 0.8267441860465116,
   'Precision_shifted': 0.7777777777777778,
   'Sensitivity_shifted': 0.7,
   'Specificity_shifted': 0.9534883720930233,
   'F1_Score_shifted': 0.7368421052631577,
   'FPR_shifted': 0.046511627906976716,
   'VME_shifted': 4.651162790697675,
   'ME_shifted': 30.0,
   'Confusion_matrix_shifted': array([[41,  2],
          [ 3,  7]])},
  {'Precision': 0.9230769230769231,
   'Sensitivity': 0.9230769230769231,
   'Specificity': 0.975,
   'F1_Score': 0.9230769230769231,
   'FPR': 0.025000000000000022,
   'VME': 2.5,
   'ME': 7.6923076923076925,
   'Confusion_matrix': array([[39,  1],
          [ 1, 12]]),
   'ROC_AUC': 0.9471153846153847,
   'Precision_shifted': 0.9230769230769231,
   'Sensitivity_shifted': 0.9230769230769231,
   'Specificity_shifted': 0.975,
   'F1_Score_shifted': 0.9230769230769231,
   'FPR_shifted': 0.025000000000000022,
   'VME_shifted': 2.5,
   'ME_shifted': 7.6923076923076925,
   'Confusion_matrix_shifted': array([[39,  1],
          [ 1, 12]])},
  {'Precision': 0.7272727272727273,
   'Sensitivity': 1.0,
   'Specificity': 0.9333333333333333,
   'F1_Score': 0.8421052631578948,
   'FPR': 0.06666666666666665,
   'VME': 6.666666666666667,
   'ME': 0.0,
   'Confusion_matrix': array([[42,  3],
          [ 0,  8]]),
   'ROC_AUC': 0.9666666666666667,
   'Precision_shifted': 0.7272727272727273,
   'Sensitivity_shifted': 1.0,
   'Specificity_shifted': 0.9333333333333333,
   'F1_Score_shifted': 0.8421052631578948,
   'FPR_shifted': 0.06666666666666665,
   'VME_shifted': 6.666666666666667,
   'ME_shifted': 0.0,
   'Confusion_matrix_shifted': array([[42,  3],
          [ 0,  8]])},
  {'Precision': 0.8333333333333334,
   'Sensitivity': 0.7142857142857143,
   'Specificity': 0.9782608695652174,
   'F1_Score': 0.7692307692307692,
   'FPR': 0.021739130434782594,
   'VME': 2.1739130434782608,
   'ME': 28.57142857142857,
   'Confusion_matrix': array([[45,  1],
          [ 2,  5]]),
   'ROC_AUC': 0.8431677018633542,
   'Precision_shifted': 0.8333333333333334,
   'Sensitivity_shifted': 0.7142857142857143,
   'Specificity_shifted': 0.9782608695652174,
   'F1_Score_shifted': 0.7692307692307692,
   'FPR_shifted': 0.021739130434782594,
   'VME_shifted': 2.1739130434782608,
   'ME_shifted': 28.57142857142857,
   'Confusion_matrix_shifted': array([[45,  1],
          [ 2,  5]])},
  {'Precision': 0.75,
   'Sensitivity': 1.0,
   'Specificity': 0.9574468085106383,
   'F1_Score': 0.8571428571428571,
   'FPR': 0.04255319148936165,
   'VME': 4.25531914893617,
   'ME': 0.0,
   'Confusion_matrix': array([[45,  2],
          [ 0,  6]]),
   'ROC_AUC': 0.9787234042553192,
   'Precision_shifted': 0.75,
   'Sensitivity_shifted': 1.0,
   'Specificity_shifted': 0.9574468085106383,
   'F1_Score_shifted': 0.8571428571428571,
   'FPR_shifted': 0.04255319148936165,
   'VME_shifted': 4.25531914893617,
   'ME_shifted': 0.0,
   'Confusion_matrix_shifted': array([[45,  2],
          [ 0,  6]])},
  {'Precision': 0.875,
   'Sensitivity': 0.7777777777777778,
   'Specificity': 0.9772727272727273,
   'F1_Score': 0.823529411764706,
   'FPR': 0.022727272727272707,
   'VME': 2.272727272727273,
   'ME': 22.22222222222222,
   'Confusion_matrix': array([[43,  1],
          [ 2,  7]]),
   'ROC_AUC': 0.8775252525252525,
   'Precision_shifted': 0.875,
   'Sensitivity_shifted': 0.7777777777777778,
   'Specificity_shifted': 0.9772727272727273,
   'F1_Score_shifted': 0.823529411764706,
   'FPR_shifted': 0.022727272727272707,
   'VME_shifted': 2.272727272727273,
   'ME_shifted': 22.22222222222222,
   'Confusion_matrix_shifted': array([[43,  1],
          [ 2,  7]])},
  {'Precision': 0.875,
   'Sensitivity': 0.875,
   'Specificity': 0.9777777777777777,
   'F1_Score': 0.875,
   'FPR': 0.022222222222222254,
   'VME': 2.2222222222222223,
   'ME': 12.5,
   'Confusion_matrix': array([[44,  1],
          [ 1,  7]]),
   'ROC_AUC': 0.9263888888888888,
   'Precision_shifted': 0.875,
   'Sensitivity_shifted': 0.875,
   'Specificity_shifted': 0.9777777777777777,
   'F1_Score_shifted': 0.875,
   'FPR_shifted': 0.022222222222222254,
   'VME_shifted': 2.2222222222222223,
   'ME_shifted': 12.5,
   'Confusion_matrix_shifted': array([[44,  1],
          [ 1,  7]])},
  {'Precision': 1.0,
   'Sensitivity': 0.9166666666666666,
   'Specificity': 1.0,
   'F1_Score': 0.9565217391304348,
   'FPR': 0.0,
   'VME': 0.0,
   'ME': 8.333333333333332,
   'Confusion_matrix': array([[41,  0],
          [ 1, 11]]),
   'ROC_AUC': 0.9552845528455284,
   'Precision_shifted': 1.0,
   'Sensitivity_shifted': 0.9166666666666666,
   'Specificity_shifted': 1.0,
   'F1_Score_shifted': 0.9565217391304348,
   'FPR_shifted': 0.0,
   'VME_shifted': 0.0,
   'ME_shifted': 8.333333333333332,
   'Confusion_matrix_shifted': array([[41,  0],
          [ 1, 11]])},
  {'Precision': 0.875,
   'Sensitivity': 1.0,
   'Specificity': 0.9782608695652174,
   'F1_Score': 0.9333333333333333,
   'FPR': 0.021739130434782594,
   'VME': 2.1739130434782608,
   'ME': 0.0,
   'Confusion_matrix': array([[45,  1],
          [ 0,  7]]),
   'ROC_AUC': 0.9891304347826088,
   'Precision_shifted': 0.875,
   'Sensitivity_shifted': 1.0,
   'Specificity_shifted': 0.9782608695652174,
   'F1_Score_shifted': 0.9333333333333333,
   'FPR_shifted': 0.021739130434782594,
   'VME_shifted': 2.1739130434782608,
   'ME_shifted': 0.0,
   'Confusion_matrix_shifted': array([[45,  1],
          [ 0,  7]])},
  {'Precision': 0.8181818181818182,
   'Sensitivity': 0.8181818181818182,
   'Specificity': 0.9523809523809523,
   'F1_Score': 0.8181818181818182,
   'FPR': 0.04761904761904767,
   'VME': 4.761904761904762,
   'ME': 18.181818181818183,
   'Confusion_matrix': array([[40,  2],
          [ 2,  9]]),
   'ROC_AUC': 0.880952380952381,
   'Precision_shifted': 0.8181818181818182,
   'Sensitivity_shifted': 0.8181818181818182,
   'Specificity_shifted': 0.9523809523809523,
   'F1_Score_shifted': 0.8181818181818182,
   'FPR_shifted': 0.04761904761904767,
   'VME_shifted': 4.761904761904762,
   'ME_shifted': 18.181818181818183,
   'Confusion_matrix_shifted': array([[40,  2],
          [ 2,  9]])},
  {'Precision': 0.8888888888888888,
   'Sensitivity': 1.0,
   'Specificity': 0.9777777777777777,
   'F1_Score': 0.9411764705882353,
   'FPR': 0.022222222222222254,
   'VME': 2.2222222222222223,
   'ME': 0.0,
   'Confusion_matrix': array([[44,  1],
          [ 0,  8]]),
   'ROC_AUC': 0.9888888888888889,
   'Precision_shifted': 0.8888888888888888,
   'Sensitivity_shifted': 1.0,
   'Specificity_shifted': 0.9777777777777777,
   'F1_Score_shifted': 0.9411764705882353,
   'FPR_shifted': 0.022222222222222254,
   'VME_shifted': 2.2222222222222223,
   'ME_shifted': 0.0,
   'Confusion_matrix_shifted': array([[44,  1],
          [ 0,  8]])},
  {'Precision': 0.9090909090909091,
   'Sensitivity': 0.9090909090909091,
   'Specificity': 0.9761904761904762,
   'F1_Score': 0.9090909090909091,
   'FPR': 0.023809523809523836,
   'VME': 2.380952380952381,
   'ME': 9.090909090909092,
   'Confusion_matrix': array([[41,  1],
          [ 1, 10]]),
   'ROC_AUC': 0.9437229437229437,
   'Precision_shifted': 0.9090909090909091,
   'Sensitivity_shifted': 0.9090909090909091,
   'Specificity_shifted': 0.9761904761904762,
   'F1_Score_shifted': 0.9090909090909091,
   'FPR_shifted': 0.023809523809523836,
   'VME_shifted': 2.380952380952381,
   'ME_shifted': 9.090909090909092,
   'Confusion_matrix_shifted': array([[41,  1],
          [ 1, 10]])},
  {'Precision': 0.9090909090909091,
   'Sensitivity': 0.8333333333333334,
   'Specificity': 0.975609756097561,
   'F1_Score': 0.8695652173913043,
   'FPR': 0.024390243902439046,
   'VME': 2.4390243902439024,
   'ME': 16.666666666666664,
   'Confusion_matrix': array([[40,  1],
          [ 2, 10]]),
   'ROC_AUC': 0.9024390243902439,
   'Precision_shifted': 0.9090909090909091,
   'Sensitivity_shifted': 0.8333333333333334,
   'Specificity_shifted': 0.975609756097561,
   'F1_Score_shifted': 0.8695652173913043,
   'FPR_shifted': 0.024390243902439046,
   'VME_shifted': 2.4390243902439024,

In [103]:
model_type = ['DT']
all_models_results_original_DT_models = {model_type: [] for model_type in model_types}

for model_type in model_types:
    for seed in random_seeds:
        model = Models(
            {"all": data[features_and_label]},
            model_type,
            "recall",
            random_seed=seed,
            test_fraction=0.20,
            verbose=False,
            output_plots=False,
        )
        output_original_DT_model = model.get_model()
        all_models_results_original_DT_models[model_type].append(output_original_DT_model)

In [104]:
all_models_results_original_DT_models

{'DT': [DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=4, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=4, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=4, random_state=0),
  DecisionTreeClassifier(max_depth=4, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=4, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0),
  DecisionTreeClassifier(max_depth=2, random_state=0)]}

### Run DT models on non-RRDR dataset and plot new confusion matrices

In [105]:
x_nonRRDR_nd = x_nonRRDR.to_numpy()
predictions = []

for model_type in all_models_results_original_DT_models.keys():
    for single_model in all_models_results_original_DT_models[model_type]:
        y_proba = single_model.predict_proba(x_nonRRDR_nd)[:,1].astype(int)
        predictions.append(y_proba)

predictions

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [106]:
#calculate new confusion matrix for each model
confusion_list = [confusion_matrix(phenotypes_nonRRDR, predictions[i]) for i in range(0,len(predictions))]

In [107]:
cm_mean = np.zeros_like(confusion_list[0],dtype=float)

for result in confusion_list:
    cm_mean += result/len(confusion_list)

cm_mean = np.round(cm_mean)

In [108]:
cm_mean

array([[206.,   0.],
       [ 10.,   0.]])

All mutations are, on average, predicted to be susceptible.